# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a53b2521d84485f3e89c90a82d3713e3dcea2fcf03e5df6b5dea54bfdf0c23858f2fd85b8217692a763c25e5e6092200e917c3e107a5bc56ee5db738ad25af1

test:
  secret_key_base: 636fdabdd528f05a2feee9a26cc7007557827fad6859e316d4f45bf69cbe9b392240b92b67aa219a46577303e126fb01aeb70b7a52ffe8aba05c58b5c1d71354

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
